# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qc < Formula
  desc "QOwnNotes command-line snippet manager"
  homepage "https://github.com/qownnotes/qc"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qownnotes/qc/releases/download/v0.3.2/qc_0.3.2_darwin_amd64.tar.gz"
      sha256 "aff9baca27f87aabbe24a1deb6fc93c68310f3bcdffa2f1028531b786b965777"

      def install
        bin.install Dir['qc']
        zsh_completion.install "misc/completions/zsh/_qc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qownnotes/qc/releases/download/v0.3.2/qc_0.3.2_darwin_arm64.tar.gz"
      sha256 "6be701be55fa2ae9ea48c28a7661941e1608343b1b1296cb1815192f551a9feb"

      def install
        bin.install Dir['qc']
        zsh_completion.install "misc/completions/zsh/_qc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qownnotes/qc/releases/download/v0.3.2/qc_0.3.2_linux_arm64.tar.gz"
      sha256 "8d3e84d0c034ddb52ec11e0da29109a254ed1ca5cd7d25ff5ba28013a419764b"

      def install
        bin.install Dir['qc']
        zsh_completion.install "misc/completions/zsh/_qc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qownnotes/qc/releases/download/v0.3.2/qc_0.3.2_linux_amd64.tar.gz"
      sha256 "17af0278a7350ce0c9da9784ad34f6469498df67880059a56db662d768570920"

      def install
        bin.install Dir['qc']
        zsh_completion.install "misc/completions/zsh/_qc"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/qownnotes/qc/releases/download/v0.3.2/qc_0.3.2_linux_armv6.tar.gz"
      sha256 "00030bc7483897f40a26d24a092bd57338fe84c7613773c7eafe626231a3aaa8"

      def install
        bin.install Dir['qc']
        zsh_completion.install "misc/completions/zsh/_qc"
      end
    end
  end

  depends_on "fzf"

  test do
    system "#{bin}/qc"
  end
end
