# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qc < Formula
  desc "QOwnNotes command-line snippet manager"
  homepage "https://github.com/qownnotes/qc"
  version "0.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qownnotes/qc/releases/download/v0.5.1/qc_0.5.1_darwin_amd64.tar.gz"
      sha256 "f1ca84ea7b18bc76f9a92ae995aa08df9742a5030286a86f2a13d260af43b871"

      def install
        bin.install Dir['qc']
        zsh_completion.install "misc/completions/zsh/_qc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/qownnotes/qc/releases/download/v0.5.1/qc_0.5.1_linux_armv6.tar.gz"
      sha256 "bc204c5a00a559f3e8ebf19cc5c42791a3052cf50dc2685de5565fb5484d3cc0"

      def install
        bin.install Dir['qc']
        zsh_completion.install "misc/completions/zsh/_qc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qownnotes/qc/releases/download/v0.5.1/qc_0.5.1_linux_arm64.tar.gz"
      sha256 "e21d356bac6d55003ab82e2d1bdb524e840e071aec223f552fbf35234642662f"

      def install
        bin.install Dir['qc']
        zsh_completion.install "misc/completions/zsh/_qc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qownnotes/qc/releases/download/v0.5.1/qc_0.5.1_linux_amd64.tar.gz"
      sha256 "4a805298c59e0077d124e987ab2e29da0595a57c2fc59719c073850b1674e2a1"

      def install
        bin.install Dir['qc']
        zsh_completion.install "misc/completions/zsh/_qc"
      end
    end
  end

  depends_on "fzf"

  test do
    system "#{bin}/qc"
  end
end
