# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qc < Formula
  desc "QOwnNotes command-line snippet manager"
  homepage "https://github.com/qownnotes/qc"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qownnotes/qc/releases/download/v0.4.0/qc_0.4.0_darwin_amd64.tar.gz"
      sha256 "cd2b9b421be1a7bf7571a6b7d1707aee3ece3f0d36bcb19780b9a136f99d9374"

      def install
        bin.install Dir['qc']
        zsh_completion.install "misc/completions/zsh/_qc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qownnotes/qc/releases/download/v0.4.0/qc_0.4.0_darwin_arm64.tar.gz"
      sha256 "75f000c54bd4ee6aaf48e1dfd8280823e7eb22f0e30f9a1573e0dae0bb2a8868"

      def install
        bin.install Dir['qc']
        zsh_completion.install "misc/completions/zsh/_qc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/qownnotes/qc/releases/download/v0.4.0/qc_0.4.0_linux_armv6.tar.gz"
      sha256 "c24ab91f1103cb33c4fab5f838184a6bcb45bf97fef4fa28f0f94019a7e98f72"

      def install
        bin.install Dir['qc']
        zsh_completion.install "misc/completions/zsh/_qc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qownnotes/qc/releases/download/v0.4.0/qc_0.4.0_linux_amd64.tar.gz"
      sha256 "5109bd8e41222fccf78525e26c973682be3ac5837f26a08d22a7e84954d0e7e7"

      def install
        bin.install Dir['qc']
        zsh_completion.install "misc/completions/zsh/_qc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qownnotes/qc/releases/download/v0.4.0/qc_0.4.0_linux_arm64.tar.gz"
      sha256 "a104ba7e485ab95d9b8e8eb0a96c6ce8b8eb73ab34458578e7b6b85874161aaf"

      def install
        bin.install Dir['qc']
        zsh_completion.install "misc/completions/zsh/_qc"
      end
    end
  end

  depends_on "fzf"

  test do
    system "#{bin}/qc"
  end
end
